ALTER TYPE payment_status RENAME VALUE 'PENDING' TO 'PENDIENTE';
ALTER TYPE payment_status RENAME VALUE 'CONFIRMED' TO 'CONFIRMADO';
ALTER TYPE payment_status RENAME VALUE 'REJECTED' TO 'RECHAZADO';
ALTER TYPE payment_status RENAME VALUE 'EXPIRED' TO 'EXPIRADO';
ALTER TYPE payment_status RENAME VALUE 'CANCELLED' TO 'CANCELADO';
