import React, { useEffect, useState } from 'react';
import { api, type Product, variantLabel } from '../../api';

export function ProductDetailPage({ productId, onCartChange, onBack }: { productId: string; onCartChange: () => void; onBack: () => void }) {
  const [product, setProduct] = useState<Product | null>(null);
  const [selectedVariantId, setSelectedVariantId] = useState('');
  const [message, setMessage] = useState('');
  useEffect(() => { api.getProduct(productId).then((next) => { setProduct(next); setSelectedVariantId(next.variants.find((variant) => variant.isActive)?.id ?? ''); }).catch((reason: Error) => setMessage(reason.message)); }, [productId]);
  if (!product) return <section className="mx-auto max-w-3xl px-6 py-12 text-center">{message || 'Cargando producto...'}</section>;
  const activeVariants = product.variants.filter((variant) => variant.isActive);
  const selectedVariant = activeVariants.find((variant) => variant.id === selectedVariantId) ?? activeVariants[0];
  const hasStock = (selectedVariant?.stock ?? 0) > 0;
  const addToCart = () => selectedVariant && api.addToCart(selectedVariant.id).then(() => { setMessage('Producto agregado al carrito.'); onCartChange(); }).catch((reason: Error) => setMessage(reason.message));
  return <section className="mx-auto max-w-6xl px-6 py-10"><button onClick={onBack} className="mb-4 text-sm font-semibold text-slate-600">← Volver al catálogo</button><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="grid gap-8 p-6 md:grid-cols-2 md:p-8"><div className="flex min-h-[320px] items-end rounded-2xl bg-gradient-to-br from-amber-100 via-slate-100 to-sky-200 p-8"><span className="text-8xl">⚽</span></div><div className="flex flex-col justify-center"><div className="mb-4 flex items-center gap-3"><span className="rounded-full bg-amber-100 px-2.5 py-1 text-[10px] font-semibold uppercase text-amber-800">{product.category}</span><span className={`text-sm font-semibold ${hasStock ? 'text-emerald-600' : 'text-red-600'}`}>{hasStock ? 'Disponible' : 'Agotada'}</span></div><h1 className="text-3xl font-bold">{product.name}</h1><p className="mt-3 text-slate-600">{product.description}</p><div className="mt-6"><p className="text-sm font-medium">Selecciona una variante</p><div className="mt-3 flex flex-wrap gap-3">{activeVariants.map((variant) => <button key={variant.id} type="button" onClick={() => setSelectedVariantId(variant.id)} className={`rounded-xl border px-3 py-2 text-left ${selectedVariant.id === variant.id ? 'border-slate-900 bg-slate-900 text-white' : 'border-slate-300 bg-white'}`}><div className="text-sm font-semibold">{variantLabel(variant)}</div><div className="mt-1 text-xs opacity-80">{variant.stock > 0 ? `${variant.stock} disponibles` : 'Sin stock'}</div></button>)}</div></div><div className="mt-6 flex items-end justify-between gap-4 border-t border-slate-200 pt-5"><div><p className="text-sm text-slate-500">Precio</p><p className="text-3xl font-bold">${selectedVariant?.price.toFixed(2) ?? '0.00'}</p></div><button type="button" disabled={!selectedVariant || !hasStock} onClick={addToCart} className="rounded-xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:bg-slate-300">{hasStock ? 'Agregar al carrito' : 'Sin stock'}</button></div>{message && <p className="mt-3 text-sm text-slate-600">{message}</p>}</div></div></div></section>;
}
