import React, { useEffect, useState } from 'react';
import { api, type Product } from '../../api';

export function AdminPage() {
  const [products, setProducts] = useState<Product[]>([]);
  const [message, setMessage] = useState('');
  const load = () => api.adminProducts().then((result) => setProducts(result.items)).catch((reason: Error) => setMessage(reason.message));
  useEffect(load, []);
  const update = (id: string, payload: { price?: number; stock?: number; isActive?: boolean }) => api.updateAdminVariant(id, payload).then(() => { setMessage('Cambios guardados.'); load(); }).catch((reason: Error) => setMessage(reason.message));
  return <section className="mx-auto max-w-6xl px-6 py-10"><div className="mb-6"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-amber-700">Operación</p><h1 className="text-3xl font-bold">Catálogo e inventario</h1><p className="mt-2 text-slate-600">Actualiza precio, stock y disponibilidad sin alterar pedidos históricos.</p></div>{message && <p className="mb-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">{message}</p>}<div className="space-y-4">{products.map((product) => <article key={product.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-bold">{product.name}</h2><p className="text-sm text-slate-500">{product.category}</p></div><span className="text-xs text-slate-500">{product.isActive ? 'Producto activo' : 'Producto inactivo'}</span></div><div className="space-y-3">{product.variants.map((variant) => <div key={variant.id} className="grid gap-3 border-t border-slate-100 pt-3 sm:grid-cols-[1fr_120px_120px_auto] sm:items-end"><div><p className="font-semibold">{Object.values(variant.attributes).join(' - ') || variant.sku}</p><p className="text-xs text-slate-500">{variant.id}</p></div><label className="text-sm">Precio<input type="number" min="0" step="0.01" defaultValue={variant.price} onBlur={(event) => update(variant.id, { price: Number(event.target.value) })} className="mt-1 w-full rounded-lg border border-slate-300 px-2 py-1" /></label><label className="text-sm">Stock<input type="number" min="0" step="1" defaultValue={variant.stock} onBlur={(event) => update(variant.id, { stock: Number(event.target.value) })} className="mt-1 w-full rounded-lg border border-slate-300 px-2 py-1" /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" defaultChecked={variant.isActive} onChange={(event) => update(variant.id, { isActive: event.target.checked })} /> Activa</label></div>)}</div></article>)}</div></section>;
}
