import React, { useState } from 'react';
import { api, type Cart } from './api';
import { formatCOP } from './currency';

export function CartView({ cart, onChange, onCheckout }: { cart: Cart; onChange: () => void; onCheckout: () => void }) {
  const [message, setMessage] = useState('');
  const updateQuantity = (id: string, quantity: number) => api.updateCartItem(id, quantity).then(onChange).catch((reason: Error) => setMessage(reason.message));
  const remove = (id: string) => api.removeCartItem(id).then(onChange).catch((reason: Error) => setMessage(reason.message));
  return <section className="mx-auto max-w-4xl px-6 py-10"><h1 className="mb-6 text-3xl font-bold">Carrito</h1>{message && <p className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{message}</p>}{cart.items.length === 0 ? <div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-600">Tu carrito está vacío.</div> : <><div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm">{cart.items.map((item) => <div key={item.id} className="flex flex-col gap-3 border-b border-slate-200 py-4 last:border-b-0 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{item.productName}</p><p className="text-sm text-slate-600">{item.variantLabel}</p><p className="text-sm text-slate-500">{formatCOP(item.unitPrice)} c/u</p></div><div className="flex items-center gap-3"><button aria-label="Reducir cantidad" className="rounded border px-2" disabled={item.quantity === 1} onClick={() => updateQuantity(item.id, item.quantity - 1)}>−</button><span>{item.quantity}</span><button aria-label="Aumentar cantidad" className="rounded border px-2" onClick={() => updateQuantity(item.id, item.quantity + 1)}>+</button><button onClick={() => remove(item.id)} className="ml-2 text-sm text-red-700">Eliminar</button></div><p className="font-semibold">{formatCOP(item.subtotal)}</p></div>)}</div><div className="mt-6 flex flex-col gap-4 rounded-xl bg-slate-900 p-5 text-white sm:flex-row sm:items-center sm:justify-between"><span>Total <strong>{formatCOP(cart.total)}</strong></span><button onClick={onCheckout} className="rounded-lg bg-amber-400 px-4 py-3 font-bold text-slate-950">Continuar al checkout</button></div></>}</section>;
}
