import React, { useState } from 'react';
import { api, type Cart, type Session, type PaymentMethod } from './api';

export function CheckoutView({ cart, session, onCompleted }: { cart: Cart; session: Session | null; onCompleted: (id: string, account?: Session) => void }) {
  const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>('WHATSAPP_TRANSFER');
  const [name, setName] = useState(session?.name ?? '');
  const [email, setEmail] = useState(session?.email ?? '');
  const [phone, setPhone] = useState('');
  const [message, setMessage] = useState('');
  const submit = (event: React.FormEvent) => { event.preventDefault(); setMessage(''); api.checkout({ paymentMethod, guestCheckout: !session, customer: { name, email, ...(phone ? { phone } : {}) } }).then((result) => onCompleted(result.orderId, result.account)).catch((reason: Error) => setMessage(reason.message)); };
  return <section className="mx-auto max-w-3xl px-6 py-10"><h1 className="mb-6 text-3xl font-bold">Checkout</h1><form onSubmit={submit} className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Nombre<input required value={name} onChange={(event) => setName(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /></label><label className="text-sm font-medium">Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /></label></div><label className="mt-4 block text-sm font-medium">Teléfono <span className="font-normal text-slate-500">(obligatorio para contraentrega)</span><input required={paymentMethod === 'CASH_ON_DELIVERY'} value={phone} onChange={(event) => setPhone(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /></label><fieldset className="mt-6"><legend className="text-sm font-semibold">Método de pago</legend><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className={`rounded-lg border p-3 ${paymentMethod === 'WHATSAPP_TRANSFER' ? 'border-slate-900' : 'border-slate-200'}`}><input type="radio" name="payment" checked={paymentMethod === 'WHATSAPP_TRANSFER'} onChange={() => setPaymentMethod('WHATSAPP_TRANSFER')} /> <span className="ml-2">Transferencia WhatsApp</span><span className="mt-1 block text-xs text-slate-500">Confirmación manual por administración.</span></label><label className={`rounded-lg border p-3 ${paymentMethod === 'CASH_ON_DELIVERY' ? 'border-slate-900' : 'border-slate-200'}`}><input type="radio" name="payment" checked={paymentMethod === 'CASH_ON_DELIVERY'} onChange={() => setPaymentMethod('CASH_ON_DELIVERY')} /> <span className="ml-2">Contraentrega</span><span className="mt-1 block text-xs text-slate-500">Disponible para entrega inmediata.</span></label></div></fieldset><div className="mt-6 rounded-lg bg-slate-100 p-4"><p className="text-sm font-semibold">Total calculado por el backend</p><p className="mt-1 text-2xl font-bold">${cart.total.toFixed(2)}</p></div>{message && <p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{message}</p>}<button disabled={cart.items.length === 0} className="mt-6 w-full rounded-lg bg-slate-900 px-4 py-3 font-semibold text-white disabled:bg-slate-300">Confirmar pedido</button></form></section>;
}
